:pushpin: Remove numpy max version specifier
Fixes `ValueError: numpy.ndarray size changed, may indicate binary
incompatibility. Expected 88 from C header, got 80 from PyObject` error
on M1 macs.
- Essentially, it looks like this is due to an API change in numpy for
versions >= 1.2.0 (source: https://stackoverflow.com/a/69528768)

Example error log:
```
Traceback (most recent call last):
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/train.py", line 2, in <module>
    import texthero as hero
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/texthero/__init__.py", line 6, in <module>
    from . import preprocessing
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/texthero/preprocessing.py", line 10, in <module>
    import pandas as pd
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```