:heavy_plus_sign: :bug: Re-add required dependency: `pyarrow`
Accidentally removed in #171.

Fixes `ModuleNotFoundError: No module named 'pyarrow'` errors.

Example error log:
```
Traceback (most recent call last):
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/train.py", line 9, in <module>
    from local_module import (
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/local_module/__init__.py", line 14, in <module>
    from local_module.train import tune_model
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/local_module/train.py", line 9, in <module>
    import xgboost_ray as xgbr
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/xgboost_ray/__init__.py", line 1, in <module>
    from xgboost_ray.main import RayParams, train, predict
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/xgboost_ray/main.py", line 68, in <module>
    from xgboost_ray.matrix import RayDMatrix, combine_data, \
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/xgboost_ray/matrix.py", line 24, in <module>
    from xgboost_ray.data_sources import DataSource, data_sources, RayFileType
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/xgboost_ray/data_sources/__init__.py", line 6, in <module>
    from xgboost_ray.data_sources.ml_dataset import MLDataset
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/xgboost_ray/data_sources/ml_dataset.py", line 4, in <module>
    from ray.util.data import MLDataset as MLDatasetType
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/ray/util/data/__init__.py", line 7, in <module>
    from ray.util.data.parquet import read_parquet
  File "/Users/teo/Developer/personal/ray-summit-demo-2021-public/.venv/lib/python3.9/site-packages/ray/util/data/parquet.py", line 5, in <module>
    import pyarrow.parquet as pq
ModuleNotFoundError: No module named 'pyarrow'
```